### ISSUE TITLE
Improve parameter handling

### ISSUE THREAD

**Issue by redaxmedia** [Zod-/jsVideoUrlParser#11]
Thank you for providing the <code>params</code> options... it works as it should be but fails / runs into busy waiting (infinity loop) when I passed invalid / undefined params. In my project it even stops the whole Javascript to process without returning na error or warning.

1. Simplify the whole parameter handling and remove the extra magic that ruins the performance
<pre>
while (tokens = re.exec(qs)) {
     params[decodeURIComponent(tokens[1])] = decodeURIComponent(tokens[2]);
}
</pre>
1. If you want to keep it, set the tokens var outside the while
1. Prevent the processing of emtpy or invalid params
1. Unit testing

**Comment by Zod-** [comment]
Can you give me an example with what that happened?

**Comment by redaxmedia** [comment]
Ok, me code looks like this:

<pre>
project.getVideoUrl = function (url, options) {
        var videoInfo = '',
            videoUrl = '';

        if (typeof win.urlParser === 'object') {
            videoInfo = win.urlParser.parse(url);
            if (typeof  videoInfo === 'object' && typeof videoInfo.provider === 'string') {
                videoUrl = win.urlParser.create({
                    videoInfo: videoInfo,
                    format: 'embed',
                    params: typeof options === 'object' && typeof options[videoInfo.provider] === 'object' ? options[videoInfo.provider] : {}
                });
            }
            if (videoUrl.length) {
                return videoUrl;
            } else {
                return false;
            }
        }
        return false;
    };
</pre>

The check <code>typeof options === 'object'</code> is essential, otherwise it runs into the infinite loop.

**Comment by Zod-** [comment]
I can't seem to find the bug. Could you provide some test data that causes the infinite loop?

**Comment by redaxmedia** [comment]
Strange, I cannot reproduce it too^^ ... however, it will not hurt to check for params.length before you start the whole processing - I close this issue for now

**Comment by Zod-** [comment]
I will rewrite some parts and add more tests anyway.
