### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by redaxmedia** [Zod-/jsVideoUrlParser#16]
The updates for Node.js broke the whole library!

<pre>
Warning: ReferenceError: Can't find variable: module
</pre>

**Comment by Zod-** [comment]
This is a bit weird since there are only [3 occurrences](https://github.com/Zod-/jsVideoUrlParser/blob/master/dist/jsVideoUrlParser.js#L52-L54) and 2 of those are checks if it's available. 

How are you using it exactly?

**Comment by Zod-** [comment]
Yeah it's supposed to be `'undefined'` instead of `undefined`. I'll fix it right away

**Comment by redaxmedia** [comment]
Correct it is undefined vs. 'undefined' ... I suggest

<pre>
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  module.exports = urlParser;
}
</pre>

**Comment by Zod-** [comment]
I think that should be all

**Comment by redaxmedia** [comment]
Thank you for hotfixing the issue.
