### ISSUE TITLE
Not getting the current video id from the vimeo

### ISSUE THREAD

**Issue by deepakunnikrishnan** [Zod-/jsVideoUrlParser#17]
I tried parsing the below vimeo url. Instead of the actual id '155463564', it returns '1' from the '1minute'.
Can you help me out ?
https://vimeo.com/groups/1minute/videos/155463564

**Comment by Zod-** [comment]
Haven't seen that kind of links before. Sure I'll add it to the regex.

**Comment by Zod-** [comment]
Nevermind I didn't check explicitly for the group urls so it found the 1 instead of the id.
