### ISSUE TITLE
How to use this plugin with AngularJS (Ionic Framework)

### ISSUE THREAD

**Issue by kalimulhaq** [Zod-/jsVideoUrlParser#24]
I want to use this plugin in AngularJS - Ionic Framework.

Please help me

**Comment by Zod-** [comment]
I don't know much about AngularJS, but since it's in the browser it should be enough to just include the .js file on your website. The parser will be in the global scale.

`<script type="text/javascript" src="js/jsVideoUrlParser.min.js"></script>`
```
angular.module('ionicApp', ['ionic']).controller('MainCtrl', function($scope) {
  //...
  var videoInfo = urlParser.parse('http://www.youtube.com/watch?v=HRb7B9fPhfA');
 //...
});
```

**Comment by Kaz-** [comment]
Hey :) Great module, could you add this line to your bower.json so it's loaded automatically ?

`  "main": "./dist/jsVideoUrlParser.min.js",`

**Comment by Zod-** [comment]
Sure
