### ISSUE TITLE
Vimeo class in global namespace clashes with Vimeo class official Vimeo player.

### ISSUE THREAD

**Issue by rubylibre** [Zod-/jsVideoUrlParser#25]
The Vimeo plugin has the class Vimeo. When installed via bower it resides in the global namespace where it clashes official vimeo player which also uses Vimeo. My quick and dirty solution is to wrap only the plugins in:
```
(function() {
  // plugins
}).call(this);
```

**Comment by Zod-** [comment]
Could also rename all the plugins to something like `VimeoParserPlugin`. Not sure what would be considered as a good solution here.

**Comment by rubylibre** [comment]
Another option is to change the grunt build (where the concatenation of the plugins files is wrapped in an anonymous function. Or maybe wrap everything and do 
```
window.urlParser = new UrlParser();
```
When using it via bower it won't pollute the global namespace whatever names are used.

**Comment by Zod-** [comment]
I've been away on holiday for a while. I will work on this soon.

**Comment by Zod-** [comment]
@rubylibre This should be it if you want to take a look.
