### ISSUE TITLE
Twitch Clips not supported 

### ISSUE THREAD

**Issue by Kaz-** [Zod-/jsVideoUrlParser#28]
Hey :) ! I'm using your plugin on my fresh project, and I noticed they were no support for parsing Twitch Clips (new twitch feature for 30 sec video).
A twitch clip url looks like this : https://clips.twitch.tv/pokelawls/VictoriousBearFailFish . 

For now the parser considers this like a "stream".

 I tried to add Twitch Clip support to your project so I could make a pull request but I'm just so terrible with RegExes, I couldn't get something working :( . 

If I make all the other stuff could you give me a hand for the regex part ? We just need to detect if there is "clips." in front of twitch.tv , and then just get this string "pokelawls/VictoriousBearFailFish".

**Comment by Zod-** [comment]
This probably should be treated as a new format rather than being a video too, right?

**Comment by Kaz-** [comment]
Hmm shouldn't we add a mediaType 'clips' to the Twitch plugin ? Or should we add a new plugin "TwitchClips' ?

**Comment by Zod-** [comment]
Yeah I meant new mediaType and it should be in the same Plugin.

**Comment by Zod-** [comment]
I will work on it when I will find some time this weekend. 

A tip tho: When working with regex it helps a lot when you have a visualizer.
![](http://i.imgur.com/IYjHLhc.png)

I'm using [Atom](https://atom.io/) with the [regex-railroad-diagram](https://atom.io/packages/regex-railroad-diagram) package that will display the regex when having a cursor on it. You can also use websites like [Regexper](https://regexper.com/) or others.

**Comment by Zod-** [comment]
@Kaz- this should be it if you want to give it a try before I release it.

**Comment by Kaz-** [comment]
Just switched to Atom to practice regexes ! Thanks for the package :) ! 

I tried your commit and it seems to be working just great ! Nice work 👍  !
