### ISSUE TITLE
Problem parsing Twitch VOD/Clips urls

### ISSUE THREAD

**Issue by pateldhruv1993** [Zod-/jsVideoUrlParser#31]
If you try to parse a channel/stream url the parser works fine. But when you put in a VOD url or Clips url the parser still thinks its a stream url.

For e.g. : 
https://www.twitch.tv/moonmoon_ow = { channel: moonmoon_ow, mediatype: stream}

https://www.twitch.tv/videos/164368461 = {channel: videos, mediatype: stream}

https://clips.twitch.tv/EndearingLuckyElkHeyGirl = {channel: EndearingLuckyElkHeyGirl , mediatype: stream}

So I'm guessing the code just defines the first parameter after the domain name as channel and everything as a stream mediatype

**Comment by Zod-** [comment]
Looks like they switched video url formats. Before it used to be `channelName/v/videoId`. And clips used to include the channel too. I'll change it.

**Comment by Zod-** [comment]
Thanks for telling me about the update. Should all be working now again.
