### ISSUE TITLE
UglifyJS error during webpack traspilation

### ISSUE THREAD

**Issue by thsmrtone1** [Zod-/jsVideoUrlParser#43]
First thing's first, I am not a javascript pro, nor am I a webpack wizard, so bear with me while I try to convey my issue.

When running `webpack -p` for my project, I'm getting an error:

```
ERROR  Failed to compile with 1 errors

notification.js from UglifyJs
Name expected [notification.js:400,6]
```

After some research it appears this is due to webpack trying to run the ES6 code from js-video-url-parser's 'lib' directory through UglifyJS. So my workaround to get this package to work is to add 'js-video-url-parser' to the list of excludes in webpack.config.js.

Upon even more research, it appears that the 'js-video-url-parser' will transpile/uglify as designed if webpack uses the pre-transpiled version located in the 'dist' directory, but webpack will not use this version unless the 'modules' field in package.json is set to 'dist/jsVideoUrlParser.js'.

So I guess my proposal is to add a field in package.json `"module": "dist/jsVideoUrlParser.js"`.

If anyone else has any further input to this issue please tell me I'm not crazy.

**Comment by Zod-** [comment]
@thsmrtone1 Use a more recent uglifier that supports ES6. From [this](https://github.com/mishoo/UglifyJS2/issues/659) issue you can use [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) or [uglify-js@3](https://github.com/mishoo/UglifyJS2) directly.
