### ISSUE TITLE
Twitch Parser Issue

### ISSUE THREAD

**Issue by markoj3s** [Zod-/jsVideoUrlParser#47]
Hi Zod-,

I just noticed that for twitch links,

```https://www.twitch.tv/<username>/clip/<clip name>```

is returning a mediaType "stream" instead of "clip".

**Comment by Zod-** [comment]
Looks like a new format, I'll add it

**Comment by Zod-** [comment]
it's considering it a stream because it has the username as well. It actually gets the id properly but since I didn't see both the username and id in the urls before I didn't consider that case. Not really sure how to do this right now.

**Comment by Zod-** [comment]
Added in 6507574d562e0bf4055c9a4f537a04530e0dd88a

**Comment by Zod-** [comment]
Released in [0.3.2](https://github.com/Zod-/jsVideoUrlParser/releases/tag/0.3.2)
