### ISSUE TITLE
Vimeo `shortImage` and `longImage` are not supported.

### ISSUE THREAD

**Issue by mikepanayotov** [Zod-/jsVideoUrlParser#51]
Vimeo `shortImage` and `longImage` are not supported.

You can get Vimeo thumbnail without API, just build an URL like this:
`https://i.vimeocdn.com/video/{video_id} _640.jpg`

**Comment by Zod-** [comment]
Added in a96d994d64da2eb28f41f5756ca8ddbd8b9f4c9f
Because of the dynamic nature of width/height in the urls I added them as special parameters.
```javascript
> urlParser.parse('https://i.vimeocdn.com/video/97276391_500x123.webp');
{
      provider: 'vimeo',
      id: '97276391',
      mediaType: 'video',
      imageWidth: 500,
      imageHeight: 123,
      imageExtension: '.webp',
}

> urlParser.create({
    videoInfo: {
      provider: 'vimeo',
      id: '97276391',
      mediaType: 'video'
    },
    format: 'image'
  })
'https://i.vimeocdn.com/video/97276391.webp'

> urlParser.create({
    videoInfo: {
      provider: 'vimeo',
      id: '97276391',
      mediaType: 'video',
      imageWidth: 500
    },
    format: 'image'
  })
'https://i.vimeocdn.com/video/97276391_500.webp'

> urlParser.create({
    videoInfo: {
      provider: 'vimeo',
      id: '97276391',
      mediaType: 'video',
      imageWidth: 500,
      imageHeight: 123,
    },
    format: 'image'
  })
'https://i.vimeocdn.com/video/97276391_500x123.webp'

> urlParser.create({
    videoInfo: {
      provider: 'vimeo',
      id: '97276391',
      mediaType: 'video',
      imageExtension: '.png'
    },
    format: 'image'
  })
'https://i.vimeocdn.com/video/97276391.png'
```

**Comment by Zod-** [comment]
Released in [0.3.2](https://github.com/Zod-/jsVideoUrlParser/releases/tag/0.3.2)

**Comment by mixalistzikas** [comment]
https://vimeo.com/265334448
https://i.vimeocdn.com/video/265334448_640.jpg

This jpg is not from this video...
Am I losing something?

This is wrong (https://i.vimeocdn.com/video/{video_id} _640.jpg)

**Comment by Zod-** [comment]
I can't believe I didn't actually check both the video and the thumbnail while making it 🤦‍♂. Well looks like this feature won't work for Vimeo then.

**Comment by Zod-** [comment]
Removed the feature in [0.4.2](https://github.com/Zod-/jsVideoUrlParser/releases/tag/0.4.2) since it's not possible to link the image to the video as far as I can till.
