### ISSUE TITLE
Add DailyMotion image format

### ISSUE THREAD

**Issue by nehloo** [Zod-/jsVideoUrlParser#52]
I tried to push this update to the repo, but I don't have permissions for a pull request.

Proposed changes to file:
jsVideoUrlParser/lib/provider/dailymotion.js

```
...
this.formats = {
    short: this.createShortUrl,
    long: this.createLongUrl,
    embed: this.createEmbedUrl,
    image: this.createImageUrl
  };
...
Dailymotion.prototype.createImageUrl = function(vi) {
  return this.createUrl('//www.dailymotion.com/thumbnail/video/', vi);
};
```

**Comment by Zod-** [comment]
Released in [0.3.3](https://github.com/Zod-/jsVideoUrlParser/releases/tag/0.3.3)
