### ISSUE TITLE
Add TeacherTube?

### ISSUE THREAD

**Issue by queejie** [Zod-/jsVideoUrlParser#53]
Thanks for this great utility!  I've been trying to add TeacherTube into the library, but my abilities with regular expressions are near zero.  I think it would be pretty straightforward to add for someone who has done it before.  Wondering if you might consider adding it?

**Comment by Zod-** [comment]
Can you provide some sample URLs with possible formats?

Writing RegEx is a bit easier when you use some diagram tool.
![image](https://user-images.githubusercontent.com/5775094/57652873-df35c080-75d0-11e9-9594-a7cd7e6fe530.png)

Atom and VS Code both have the RegEx Railroad Diagram addons that show the live graph of the regex when you edit them. There are also online tools like [Regexper](https://regexper.com/#%28vimeo%28%3F%3Acdn%7Cpro%29%3F%29%5C.com%5C%2F%28%3F%3A%28%3F%3Achannels%5C%2F%5B%5Cw%5D%2B%7C%28%3F%3A%28%3F%3Aalbum%5C%2F%5Cd%2B%7Cgroups%5C%2F%5B%5Cw%5D%2B%7Cstaff%5C%2Fframe%29%5C%2F%29%3Fvideos%3F%29%5C%2F%29%3F%28%5Cd%2B%29%28%3F%3A_%28%5Cd%2B%29%28%3F%3Ax%28%5Cd%2B%29%29%3F%29%3F%28%5C.%5Cw%2B%29%3F).

**Comment by queejie** [comment]
Full page:
https://www.teachertube.com/video/les-homophones-ces-ses-la-rgle-488055

Embedded:
//www.teachertube.com/embed/video/488055

Image:
https://cdn.teachertube.com/uploads/2019/05/14/488055/fra-ortho-homophones-ces:ses-nouvelle-video000.jpg

The last one isn't going to be workable because of the datea, but there seems to be code in the PHP change that might give a clue:
https://github.com/ytdl-org/youtube-dl/commit/837b0617100f20b40a4b831439263c131a59aadb

**Comment by queejie** [comment]
Worst case, I could use this image, if there is no way to get one:
https://www.teachertube.com/frontend/themes/default/assets/images/default_video_thumb.jpg

**Comment by Zod-** [comment]
Yeah I didn't find a way to get thumbnails with just the video id.
I added support for video, audio, document, group, channel, collection and released it in [0.4.0](https://github.com/Zod-/jsVideoUrlParser/releases/tag/0.4.0)
