### ISSUE TITLE
Typescript Definition?

### ISSUE THREAD

**Issue by jemhuntr** [Zod-/jsVideoUrlParser#55]
Hey, thanks for this lib!

Is there any way we can have typescript typings for this package? There doesn't seem to be any definitions either locally or on DefinitelyTyped.

**Comment by Zod-** [comment]
How would I create those?

**Comment by jemhuntr** [comment]
I believe the ideal way would be to convert the project to typescript progressively (due to the relatively small codebase size), but that may involve too much work up front (and would definitely involve a lot of modifications with the build system). Also, that's something that might not be on your radar for this project.

Maybe just adding `.d.ts` type definitions for each js file might be ideal.

I could help set it up, but unfortunately I don't think I'll have much free time for the next several weeks.
