### ISSUE TITLE
Handle non existing Youtube imageQuality-ies

### ISSUE THREAD

**Issue by ligne13** [Zod-/jsVideoUrlParser#61]
Hi,

This is a not bug in this library, but a question.

I want to get the URL of a Youtube image at the highest resolution available:
```js
const url = urlParser.create({
            videoInfo: parse,
            params: {
              imageQuality: 'maxresdefault'
            },
            format: 'shortImage'
          });
```
Sometimes Youtube videos do not provide _maxresdefault_ images and the URL return a 404. I need to test that a _maxresdefault_ image exists and if not, get the _hqdefault_ quality. But I cannot test the existence of the Youtube URL (with fetch or axios) because of CORS restrictions.

How I can test that a CORS URL is not a 404 ?

thanks

**Comment by Zod-** [comment]
You can use the youtube API to get an actual list of images/thumbnails for a video
