### ISSUE TITLE
[Feature request] livestream.com support (Vimeo)

### ISSUE THREAD

**Issue by Benimation** [Zod-/jsVideoUrlParser#68]
Vimeo uses the livestream.com domain for their livestream videos.

**Comment by Zod-** [comment]
livestream used to be its own platform and I don't think you can cross-use the ids. It probably has to be its own provider until they decide to merge their services in the future.

**Comment by Benimation** [comment]
It looks like they eventually did merge the services into just the vimeo.com domain, so I'm closing this request! :)
