### ISSUE TITLE
Add grunt support

### ISSUE THREAD

**Issue by redaxmedia** [Zod-/jsVideoUrlParser#7]
Please add grunt support:

Utilize the uglify task for your dist:
<em>(you better rename the folder /release to /dist to meet global standards)</em>

<pre>
grunt dist
</pre>

What about a custom dist:

<pre>
grunt dist -dailymotion -youtube
</pre>

JSHint or JSCS:

<pre>
grunt jshint
</pre>

<pre>
grunt jscs
</pre>

**Comment by Zod-** [comment]
Like this?

**Comment by redaxmedia** [comment]
Looks fine, let me close that issue.
