### ISSUE TITLE
Embed format for url creation and options handling

### ISSUE THREAD

**Issue by redaxmedia** [Zod-/jsVideoUrlParser#9]
What about an embed format:

<pre>
urlParser.create({
    videoInfo: urlParser.parse('http://www.youtube.com/watch?feature=player_embedded&v=HRb7B9fPhfA'),
    format: 'embed'
  });
</pre>

That outputs:

<pre>
//www.youtube.com/embed/HRb7B9fPhfA
</pre>

What about options handling:

<pre>
urlParser.create({
    videoInfo: urlParser.parse('http://www.youtube.com/watch?feature=player_embedded&v=HRb7B9fPhfA'),
    format: 'embed',
    options: {
               enablejsapi: 1,
               autoplay: 1,
               loop: 1,
               rel: 0,
               showinfo: 0,
               vq: 'large'
    }
  });
</pre>

That outputs:

<pre>
//www.youtube.com/embed/HRb7B9fPhfA?enablejsapi=1&autoplay=1&loop=1&playlist=HRb7B9fPhfA&rel=0&showinfo=0&vq=large
</pre>

Here comes some inspiration from the "project" I'm currently working on, it is using your great lib:

<pre>
project.getVideoUrl = function (url, options) {
        var videoInfo = '',
            videoUrl = '',
            i;

        if (typeof win.urlParser === 'object') {
            videoInfo = win.urlParser.parse(url);

            /* handle video */

            if (typeof videoInfo === 'object' && typeof videoInfo.id === 'string') {

                /* dailymotion */

                if (videoInfo.provider === 'dailymotion') {
                    videoUrl = '//www.dailymotion.com/embed/video/' + videoInfo.id;
                }

                /* vimeo */

                if (videoInfo.provider === 'vimeo') {
                    videoUrl = '//player.vimeo.com/video/' + videoInfo.id;
                }

                /* youtube */

                if (videoInfo.provider === 'youtube') {
                    videoUrl = '//www.youtube.com/embed/' + videoInfo.id;
                }
            } else {
                return false;
            }

            /* process options */

            if (typeof options === 'object' && typeof options[videoInfo.provider] === 'object') {
                for (i in options[videoInfo.provider]) {
                    if (Object.keys(options[videoInfo.provider])[0] === i) {
                        videoUrl += '/?';
                    } else {
                        videoUrl += '&';
                    }
                    videoUrl += i + '=' + options[videoInfo.provider][i];

                    /* youtube hack */

                    if (videoInfo.provider === 'youtube' && i === 'loop' && options[videoInfo.provider]['loop'] === 1) {
                        videoUrl += '&playlist=' + videoInfo.id;
                    }
                }
            }
            return videoUrl;
        }
        return false;
};
</pre>

My unit testing data:

<pre>
/* input */
https://www.dailymotion.com/video/xxxxxx
https://www.vimeo.com/123456789
https://www.youtube.com/watch/?v=123456789
https://www.dailymotion.com
https://www.vimeo.com
https://www.youtube.com

/* output */
//www.dailymotion.com/embed/video/xxxxxx/?autoplay=1&loop=1
//player.vimeo.com/video/123456789/?autoplay=1&loop=1
//www.youtube.com/embed/123456789/?autoplay=1&loop=1&playlist=123456789
false,
false,
false
</pre>

1. I'm using protocol relative urls for the embed urls
2. youtube loop options needs a hack -> need for &playlist=video id

Let me know what I think :-)

**Comment by Zod-** [comment]
I think I will add the options in the parser too. And I also need to add a way to turn options on or off when creating the url. Maybe by just using a second object like you did.
So by default it would create the url without any parameters (playlistId, startTime, ...) and you just add the parameters you want.

**Comment by redaxmedia** [comment]
Fine, glad you like my suggestions :-) Let me know if I can help...

**Comment by Zod-** [comment]
Should I just add the protocol via a parameter?

```javascript
urlParser.create({
   videoInfo: ... ,
   protocol: ''
})
```

**Comment by Zod-** [comment]
Took a while but here it goes
https://github.com/Zod-/jsVideoUrlParser/releases/tag/0.1.3

I also added more stuff in the readme

**Comment by redaxmedia** [comment]
Thank you so much, I will try this at my office on Monday...
